/**
 * AUTO-GENERATED by @stratawp/vite-plugin from block.json — do not edit.
 *
 * Regenerate by building the theme (`pnpm build`). The committed copy is
 * verified by the `contracts:types:check` drift gate.
 *
 * Block: strata-store/feature-card
 */

export interface FeatureCardAttributes {
  description: string
  icon: string
  iconBackgroundColor: string
  title: string
}
