import prettier from 'prettier'

/**
 * block.json -> TypeScript attribute-type codegen.
 *
 * Given a parsed block.json, emits a deterministic, prettier-clean
 * `block-attributes.ts` file exporting an interface that describes the block's
 * attributes. The block's `edit.tsx` consumes this interface so the editor
 * props stay in lockstep with block.json, and a drift gate
 * (`scripts/check-types-drift.mjs`) diffs the committed output to keep them
 * in sync.
 *
 * JSON -> TS type map:
 *   string            -> string
 *   number | integer  -> number
 *   boolean           -> boolean
 *   array             -> unknown[]
 *   object            -> Record<string, unknown>
 *   (missing/unknown) -> unknown
 *
 * Optionality: an attribute with a `default` is REQUIRED; an attribute without
 * a `default` is optional (`?`).
 */

/**
 * A parsed block.json (only the fields the codegen needs).
 *
 * `attributes` is intentionally `Record<string, unknown>` so the scanned
 * `BlockMetadata` (which types attributes loosely) is assignable; each entry is
 * narrowed to {@link BlockAttributeSchema} internally.
 */
export interface BlockJsonInput {
  name?: string
  attributes?: Record<string, unknown>
}

/** A single attribute schema entry from block.json's `attributes` map. */
export interface BlockAttributeSchema {
  type?: string
  default?: unknown
  [key: string]: unknown
}

/** The result of generating a block's attribute types. */
export interface GeneratedBlockTypes {
  /** Always `block-attributes.ts` — written next to the block's block.json. */
  fileName: string
  /** Prettier-clean TypeScript source for the attribute interface. */
  content: string
}

/** Map a block.json attribute `type` to its TypeScript equivalent. */
function mapJsonTypeToTs(jsonType: string | undefined): string {
  switch (jsonType) {
    case 'string':
      return 'string'
    case 'number':
    case 'integer':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'array':
      return 'unknown[]'
    case 'object':
      return 'Record<string, unknown>'
    default:
      return 'unknown'
  }
}

/**
 * Derive a PascalCase interface base name from a block name.
 * Uses the slug portion after the namespace (`strata-basic/hero` -> `Hero`).
 */
function pascalCaseFromBlockName(blockName: string): string {
  const slug = blockName.includes('/') ? blockName.split('/').pop()! : blockName
  return slug
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

/**
 * Generate the `block-attributes.ts` source for a single block.
 *
 * The output is run through prettier with the repo config so the committed
 * file is byte-stable and `format:check` stays green.
 */
export async function generateBlockAttributeTypes(
  blockJson: BlockJsonInput
): Promise<GeneratedBlockTypes> {
  const blockName = blockJson.name ?? 'block'
  const interfaceName = `${pascalCaseFromBlockName(blockName)}Attributes`
  const attributes = blockJson.attributes ?? {}

  // Deterministic: sort attribute keys so the output never reorders on rescan.
  const sortedKeys = Object.keys(attributes).sort()

  const members = sortedKeys.map((key) => {
    const schema = (attributes[key] ?? {}) as BlockAttributeSchema
    const tsType = mapJsonTypeToTs(typeof schema.type === 'string' ? schema.type : undefined)
    // An attribute with a default is always present -> required.
    const optional = Object.prototype.hasOwnProperty.call(schema, 'default') ? '' : '?'
    return `  ${key}${optional}: ${tsType}`
  })

  const body = members.length > 0 ? `{\n${members.join('\n')}\n}` : '{}'

  const raw = `/**
 * AUTO-GENERATED by @stratawp/vite-plugin from block.json — do not edit.
 *
 * Regenerate by building the theme (\`pnpm build\`). The committed copy is
 * verified by the \`contracts:types:check\` drift gate.
 *
 * Block: ${blockName}
 */

export interface ${interfaceName} ${body}
`

  const content = await prettier.format(raw, {
    parser: 'typescript',
    semi: false,
    singleQuote: true,
    tabWidth: 2,
    useTabs: false,
    printWidth: 100,
    trailingComma: 'es5',
    arrowParens: 'always',
    endOfLine: 'lf',
  })

  return { fileName: 'block-attributes.ts', content }
}
