import type { Plugin } from 'vite'
import fg from 'fast-glob'
import { readFile, writeFile } from 'fs/promises'
import { join, dirname, relative } from 'path'
import pc from 'picocolors'
import type { BlockOptions, BlockMetadata } from '../types'

/**
 * Auto-discover and register WordPress blocks
 */
export function strataWPBlocks(options: BlockOptions = {}): Plugin {
  const {
    dir = 'src/blocks',
    autoRegister = true,
    namespace = 'stratawp',
    pattern = '**/block.json',
  } = options

  let blocks: BlockMetadata[] = []
  let rootDir: string

  return {
    name: 'stratawp:blocks',

    async configResolved(config) {
      rootDir = config.root
    },

    async buildStart() {
      // Discover blocks
      const blockJsonFiles = await fg(join(dir, pattern), {
        cwd: rootDir,
        absolute: true,
      })

      blocks = []

      for (const blockJsonPath of blockJsonFiles) {
        try {
          const content = await readFile(blockJsonPath, 'utf-8')
          const blockMeta: BlockMetadata = JSON.parse(content)

          blocks.push({
            ...blockMeta,
            _path: relative(rootDir, blockJsonPath),
            _dir: relative(rootDir, dirname(blockJsonPath)),
          } as BlockMetadata & { _path: string; _dir: string })

          this.addWatchFile(blockJsonPath)
        } catch (error) {
          this.warn(`Failed to parse block.json at ${blockJsonPath}`)
        }
      }

      if (blocks.length > 0) {
        console.log(pc.cyan(`\n  ⚒️  Found ${blocks.length} block(s):`))
        blocks.forEach((block) => {
          console.log(pc.dim(`     • ${block.name}`))
        })
        console.log()
      }
    },

    async generateBundle() {
      if (!autoRegister || blocks.length === 0) return

      // Generate PHP registration file
      const phpCode = generateBlockRegistration(blocks, namespace)

      // Write to inc/blocks.php
      const outputPath = join(rootDir, 'inc/blocks-generated.php')
      await writeFile(outputPath, phpCode, 'utf-8')

      console.log(pc.green(`  ✓ Generated block registration: inc/blocks-generated.php`))
    },

    // Hot reload blocks during development
    configureServer(server) {
      server.watcher.add(join(rootDir, dir, '**/*.json'))

      server.watcher.on('change', async (file) => {
        if (file.includes('block.json')) {
          console.log(pc.cyan('  ⚒️  Block configuration changed, reloading...'))
          server.ws.send({ type: 'full-reload' })
        }
      })
    },
  }
}

/**
 * Generate PHP code for block registration
 */
function generateBlockRegistration(blocks: BlockMetadata[], _namespace: string): string {
  const blockDirs = blocks.map((block) => {
    const blockData = block as BlockMetadata & { _dir: string }
    return blockData._dir
  })

  return `<?php
/**
 * Auto-generated block registration
 *
 * Generated by StrataWP Vite Plugin
 * Do not edit this file manually
 *
 * @package stratawp
 */

namespace StrataWP\\Blocks;

/**
 * Register all blocks
 */
function register_blocks() {
  ${blockDirs.map((dir) => `register_block_type( get_template_directory() . '/${dir}' );`).join('\n  ')}
}

add_action( 'init', __NAMESPACE__ . '\\register_blocks' );
`
}
