/**
 * Critical CSS Extraction Plugin
 *
 * Extracts critical above-the-fold CSS for faster page loads
 */
import type { Plugin } from 'vite'
import type { CriticalCSSOptions } from '../types'
import path from 'path'
import fs from 'fs'

export function wpForgeCriticalCSS(options: CriticalCSSOptions = {}): Plugin {
  const {
    enabled = true,
    templates = ['index', 'single', 'page', 'archive'],
    dimensions = { width: 1300, height: 900 },
    inline = true,
    output = 'dist/critical',
    minSize = 0,
  } = options

  if (!enabled) {
    return {
      name: 'wp-forge:critical-css',
      apply: () => false,
    }
  }

  return {
    name: 'wp-forge:critical-css',
    apply: 'build',

    async closeBundle() {
      const root = process.cwd()
      const distDir = path.join(root, 'dist')
      const templatesDir = path.join(root, 'templates')
      const outputDir = path.join(root, output)

      // Check if critical module is available
      let critical
      try {
        critical = require('critical')
      } catch {
        console.warn(
          '⚠️  Critical CSS extraction requires the "critical" package. Install it with: npm install --save-dev critical'
        )
        return
      }

      // Ensure output directory exists
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true })
      }

      console.log('📦 Extracting critical CSS...')

      // Find CSS files in dist
      const cssFiles = fs
        .readdirSync(path.join(distDir, 'css'))
        .filter((f) => f.endsWith('.css'))
        .map((f) => path.join(distDir, 'css', f))

      if (cssFiles.length === 0) {
        console.warn('  No CSS files found to extract critical CSS from')
        return
      }

      const mainCss = cssFiles[0] // Use first CSS file as source

      // Process each template
      const criticalResults: Record<string, string> = {}

      for (const template of templates) {
        const templatePath = path.join(templatesDir, `${template}.html`)

        if (!fs.existsSync(templatePath)) {
          console.warn(`  Template ${template}.html not found, skipping`)
          continue
        }

        try {
          const result = await critical.generate({
            inline: false,
            src: templatePath,
            css: [mainCss],
            dimensions: [dimensions],
            penthouse: {
              timeout: 30000,
            },
          })

          if (result.css && result.css.length > minSize) {
            criticalResults[template] = result.css

            // Write individual critical CSS files
            const criticalPath = path.join(outputDir, `${template}-critical.css`)
            fs.writeFileSync(criticalPath, result.css)

            console.log(`  ✓ ${template}: ${(result.css.length / 1024).toFixed(2)}KB`)
          }
        } catch (error) {
          console.warn(`  ✗ ${template}: Failed to extract critical CSS`)
        }
      }

      // Generate PHP loader file
      await generatePHPLoader(root, criticalResults, inline)
    },
  }
}

async function generatePHPLoader(
  root: string,
  criticalResults: Record<string, string>,
  inline: boolean
): Promise<void> {
  const incDir = path.join(root, 'inc')

  if (!fs.existsSync(incDir)) {
    fs.mkdirSync(incDir, { recursive: true })
  }

  let phpContent = `<?php
/**
 * Critical CSS Loader
 *
 * Auto-generated by WP-Forge
 * DO NOT EDIT MANUALLY
 */

namespace WPForge;

/**
 * Load critical CSS for template
 */
function load_critical_css(): void {
    $template = get_page_template_slug();

    // Normalize template name
    $template_name = basename($template, '.html');
    if (empty($template_name)) {
        $template_name = is_singular() ? 'single' : 'index';
    }

    $critical_css_map = array(
`

  // Add template mappings
  Object.keys(criticalResults).forEach((template) => {
    phpContent += `        '${template}' => '${template}-critical.css',\n`
  })

  phpContent += `    );

    if (isset($critical_css_map[$template_name])) {
        $critical_file = get_template_directory() . '/dist/critical/' . $critical_css_map[$template_name];

        if (file_exists($critical_file)) {
`

  if (inline) {
    phpContent += `            // Inline critical CSS
            echo '<style id="critical-css">';
            echo file_get_contents($critical_file);
            echo '</style>';
`
  } else {
    phpContent += `            // Link to critical CSS
            $critical_url = get_template_directory_uri() . '/dist/critical/' . $critical_css_map[$template_name];
            printf(
                '<link rel="stylesheet" href="%s" id="critical-css">',
                esc_url($critical_url)
            );
`
  }

  phpContent += `        }
    }
}

// Hook into wp_head with high priority
add_action('wp_head', __NAMESPACE__ . '\\load_critical_css', 1);
`

  fs.writeFileSync(path.join(incDir, 'critical-css-generated.php'), phpContent)
  console.log('  ✓ Generated inc/critical-css-generated.php')
}
