/**
 * Lazy Loading Plugin
 *
 * Implements lazy loading for images, CSS, and JavaScript chunks
 */
import type { Plugin } from 'vite'
import type { LazyLoadingOptions } from '../types'
import path from 'path'
import fs from 'fs'

export function strataWPLazyLoading(options: LazyLoadingOptions = {}): Plugin {
  const {
    enabled = true,
    images = 'native',
    css = true,
    chunks = true,
  } = options

  if (!enabled) {
    return {
      name: 'stratawp:lazy-loading',
      apply: () => false,
    }
  }

  return {
    name: 'stratawp:lazy-loading',
    apply: 'build',

    config() {
      if (chunks) {
        return {
          build: {
            rollupOptions: {
              output: {
                manualChunks: (id) => {
                  // Split vendor code
                  if (id.includes('node_modules')) {
                    return 'vendor'
                  }
                  // Split WordPress packages
                  if (id.includes('@wordpress/')) {
                    return 'wordpress'
                  }
                },
              },
            },
          },
        }
      }
      return {}
    },

    async closeBundle() {
      const root = process.cwd()
      await generatePHPUtilities(root, images, css)
    },
  }
}

async function generatePHPUtilities(
  root: string,
  images: string,
  css: boolean
): Promise<void> {
  const incDir = path.join(root, 'inc')

  if (!fs.existsSync(incDir)) {
    fs.mkdirSync(incDir, { recursive: true })
  }

  let phpContent = `<?php
/**
 * Lazy Loading Utilities
 *
 * Auto-generated by StrataWP
 * DO NOT EDIT MANUALLY
 */

namespace StrataWP;

`

  // Image lazy loading
  if (images !== 'none') {
    phpContent += `/**
 * Add loading="lazy" to images
 */
function add_lazy_loading_to_images( $content ) {
    if ( is_admin() || is_feed() ) {
        return $content;
    }

    // Add loading="lazy" to img tags that don't have it
    $content = preg_replace(
        '/<img(?![^>]*loading=)([^>]*)>/i',
        '<img loading="lazy"$1>',
        $content
    );

    return $content;
}

add_filter( 'the_content', __NAMESPACE__ . '\\add_lazy_loading_to_images', 20 );
add_filter( 'post_thumbnail_html', __NAMESPACE__ . '\\add_lazy_loading_to_images', 20 );

`
  }

  // CSS lazy loading
  if (css) {
    phpContent += `/**
 * Lazy load non-critical CSS
 */
function lazy_load_css( $html, $handle, $href, $media ) {
    // Skip critical CSS
    if ( strpos( $handle, 'critical' ) !== false ) {
        return $html;
    }

    // Change media to "print" and add onload to switch to "all"
    $html = str_replace(
        "media='{$media}'",
        "media='print' onload=\\"this.media='all'; this.onload=null;\\"",
        $html
    );

    // Add noscript fallback
    $noscript = sprintf(
        '<noscript><link rel="stylesheet" href="%s" media="%s"></noscript>',
        esc_url( $href ),
        esc_attr( $media )
    );

    return $html . $noscript;
}

// Uncomment to enable CSS lazy loading
// add_filter( 'style_loader_tag', __NAMESPACE__ . '\\lazy_load_css', 10, 4 );

`
  }

  phpContent += `/**
 * Preconnect to external domains
 */
function add_resource_hints( $urls, $relation_type ) {
    if ( 'preconnect' === $relation_type ) {
        $urls[] = array(
            'href' => 'https://fonts.googleapis.com',
            'crossorigin',
        );
        $urls[] = array(
            'href' => 'https://fonts.gstatic.com',
            'crossorigin',
        );
    }

    return $urls;
}

add_filter( 'wp_resource_hints', __NAMESPACE__ . '\\add_resource_hints', 10, 2 );
`

  fs.writeFileSync(path.join(incDir, 'lazy-loading-generated.php'), phpContent)
  console.log('  ✓ Generated inc/lazy-loading-generated.php')
}
