/**
 * Asset Preload Plugin
 *
 * Preloads critical assets for better performance
 */
import type { Plugin } from 'vite'
import type { PreloadOptions } from '../types'
import path from 'path'
import fs from 'fs'

export function strataWPPreload(options: PreloadOptions = {}): Plugin {
  const {
    enabled = true,
    assets = ['fonts', 'critical-css'],
    strategy = 'link-tag',
  } = options

  if (!enabled) {
    return {
      name: 'stratawp:preload',
      apply: () => false,
    }
  }

  return {
    name: 'stratawp:preload',
    apply: 'build',

    async closeBundle() {
      const root = process.cwd()
      await generatePHPPreloader(root, assets, strategy)
    },
  }
}

async function generatePHPPreloader(
  root: string,
  assets: string[],
  strategy: string
): Promise<void> {
  const incDir = path.join(root, 'inc')

  if (!fs.existsSync(incDir)) {
    fs.mkdirSync(incDir, { recursive: true })
  }

  let phpContent = `<?php
/**
 * Asset Preloader
 *
 * Auto-generated by StrataWP
 * DO NOT EDIT MANUALLY
 */

namespace StrataWP;

/**
 * Preload critical assets
 */
function preload_assets(): void {
    $preloads = array();

`

  // Add font preloading
  if (assets.includes('fonts')) {
    phpContent += `    // Preload fonts
    $font_dir = get_template_directory() . '/dist/fonts';
    $font_url = get_template_directory_uri() . '/dist/fonts';

    if ( is_dir( $font_dir ) ) {
        $fonts = glob( $font_dir . '/*.{woff2,woff}', GLOB_BRACE );
        foreach ( $fonts as $font ) {
            $font_name = basename( $font );
            $preloads[] = sprintf(
                '<link rel="preload" href="%s/%s" as="font" type="font/%s" crossorigin>',
                esc_url( $font_url ),
                esc_attr( $font_name ),
                esc_attr( pathinfo( $font, PATHINFO_EXTENSION ) )
            );
        }
    }

`
  }

  // Add critical CSS preloading
  if (assets.includes('critical-css')) {
    phpContent += `    // Preload critical CSS
    $critical_dir = get_template_directory() . '/dist/critical';
    $critical_url = get_template_directory_uri() . '/dist/critical';

    if ( is_dir( $critical_dir ) ) {
        $template_name = is_singular() ? 'single' : 'index';
        $critical_file = $critical_dir . '/' . $template_name . '-critical.css';

        if ( file_exists( $critical_file ) ) {
            $preloads[] = sprintf(
                '<link rel="preload" href="%s/%s-critical.css" as="style">',
                esc_url( $critical_url ),
                esc_attr( $template_name )
            );
        }
    }

`
  }

  // Add critical JS preloading
  if (assets.includes('critical-js')) {
    phpContent += `    // Preload critical JavaScript
    $manifest_file = get_template_directory() . '/dist/.vite/manifest.json';

    if ( file_exists( $manifest_file ) ) {
        $manifest = json_decode( file_get_contents( $manifest_file ), true );

        foreach ( $manifest as $entry ) {
            if ( isset( $entry['isEntry'] ) && $entry['isEntry'] ) {
                $preloads[] = sprintf(
                    '<link rel="modulepreload" href="%s/%s">',
                    esc_url( get_template_directory_uri() . '/dist' ),
                    esc_attr( $entry['file'] )
                );
                break; // Only preload main entry
            }
        }
    }

`
  }

  phpContent += `    // Output preload tags
    foreach ( $preloads as $preload ) {
        echo $preload . "\n";
    }
}

add_action( 'wp_head', __NAMESPACE__ . '\\preload_assets', 2 );

/**
 * DNS prefetch for external resources
 */
function dns_prefetch(): void {
    $domains = array(
        '//fonts.googleapis.com',
        '//fonts.gstatic.com',
    );

    foreach ( $domains as $domain ) {
        printf(
            '<link rel="dns-prefetch" href="%s">' . "\n",
            esc_url( $domain )
        );
    }
}

add_action( 'wp_head', __NAMESPACE__ . '\\dns_prefetch', 1 );
`

  fs.writeFileSync(path.join(incDir, 'preload-generated.php'), phpContent)
  console.log('  ✓ Generated inc/preload-generated.php')
}
