/**
 * AUTO-GENERATED by @stratawp/vite-plugin from block.json — do not edit.
 *
 * Regenerate by building the theme (`pnpm build`). The committed copy is
 * verified by the `contracts:types:check` drift gate.
 *
 * Block: strata-advanced/portfolio-grid
 */

export interface PortfolioGridAttributes {
  category: string
  columns: number
  order: string
  orderBy: string
  postsPerPage: number
}
