/**
 * AUTO-GENERATED by @stratawp/vite-plugin from block.json — do not edit.
 *
 * Regenerate by building the theme (`pnpm build`). The committed copy is
 * verified by the `contracts:types:check` drift gate.
 *
 * Block: strata-store/product-categories
 */

export interface ProductCategoriesAttributes {
  columns: number
  limit: number
  showCount: boolean
  showEmpty: boolean
}
