<?php
/**
 * Auto-generated block registration
 *
 * Generated by StrataWP Vite Plugin
 * Do not edit this file manually
 *
 * @package stratawp
 */

namespace StrataWP\Blocks;

/**
 * Register all blocks
 */
function register_blocks() {
  register_block_type( get_template_directory() . '/src/blocks/feature-card' );
  register_block_type( get_template_directory() . '/src/blocks/hero' );
  register_block_type( get_template_directory() . '/src/blocks/portfolio-grid' );
  register_block_type( get_template_directory() . '/src/blocks/team-members' );
}

add_action( 'init', __NAMESPACE__ . '\register_blocks' );
