<?php
/**
 * Auto-generated block registration
 *
 * Generated by WP-Forge Vite Plugin
 * Do not edit this file manually
 *
 * @package wp-forge
 */

namespace WPForge\Blocks;

/**
 * Register all blocks
 */
function register_blocks() {
  register_block_type( get_template_directory() . '/src/blocks/feature-card' );
  register_block_type( get_template_directory() . '/src/blocks/hero' );
}

add_action( 'init', __NAMESPACE__ . '\register_blocks' );
