<?php
/**
 * Lazy Loading Utilities
 *
 * Auto-generated by WP-Forge
 * DO NOT EDIT MANUALLY
 */

namespace WPForge;

/**
 * Add loading="lazy" to images
 */
function add_lazy_loading_to_images( $content ) {
    if ( is_admin() || is_feed() ) {
        return $content;
    }

    // Add loading="lazy" to img tags that don't have it
    $content = preg_replace(
        '/<img(?![^>]*loading=)([^>]*)>/i',
        '<img loading="lazy"$1>',
        $content
    );

    return $content;
}

add_filter( 'the_content', __NAMESPACE__ . '\add_lazy_loading_to_images', 20 );
add_filter( 'post_thumbnail_html', __NAMESPACE__ . '\add_lazy_loading_to_images', 20 );

/**
 * Lazy load non-critical CSS
 */
function lazy_load_css( $html, $handle, $href, $media ) {
    // Skip critical CSS
    if ( strpos( $handle, 'critical' ) !== false ) {
        return $html;
    }

    // Change media to "print" and add onload to switch to "all"
    $html = str_replace(
        "media='{$media}'",
        "media='print' onload=\"this.media='all'; this.onload=null;\"",
        $html
    );

    // Add noscript fallback
    $noscript = sprintf(
        '<noscript><link rel="stylesheet" href="%s" media="%s"></noscript>',
        esc_url( $href ),
        esc_attr( $media )
    );

    return $html . $noscript;
}

// Uncomment to enable CSS lazy loading
// add_filter( 'style_loader_tag', __NAMESPACE__ . '\lazy_load_css', 10, 4 );

/**
 * Preconnect to external domains
 */
function add_resource_hints( $urls, $relation_type ) {
    if ( 'preconnect' === $relation_type ) {
        $urls[] = array(
            'href' => 'https://fonts.googleapis.com',
            'crossorigin',
        );
        $urls[] = array(
            'href' => 'https://fonts.gstatic.com',
            'crossorigin',
        );
    }

    return $urls;
}

add_filter( 'wp_resource_hints', __NAMESPACE__ . '\add_resource_hints', 10, 2 );
