/**
 * AUTO-GENERATED by @stratawp/vite-plugin from block.json — do not edit.
 *
 * Regenerate by building the theme (`pnpm build`). The committed copy is
 * verified by the `contracts:types:check` drift gate.
 *
 * Block: strata-advanced/hero
 */

export interface HeroAttributes {
  backgroundImage?: string
  buttonText: string
  buttonUrl: string
  description: string
  overlayOpacity: number
  title: string
}
