<?php
/**
 * Asset Preloader
 *
 * Auto-generated by StrataWP
 * DO NOT EDIT MANUALLY
 */

namespace StrataWP;

/**
 * Preload critical assets
 */
function preload_assets(): void {
    $preloads = array();

    // Preload fonts
    $font_dir = get_template_directory() . '/dist/fonts';
    $font_url = get_template_directory_uri() . '/dist/fonts';

    if ( is_dir( $font_dir ) ) {
        $fonts = glob( $font_dir . '/*.{woff2,woff}', GLOB_BRACE );
        foreach ( $fonts as $font ) {
            $font_name = basename( $font );
            $preloads[] = sprintf(
                '<link rel="preload" href="%s/%s" as="font" type="font/%s" crossorigin>',
                esc_url( $font_url ),
                esc_attr( $font_name ),
                esc_attr( pathinfo( $font, PATHINFO_EXTENSION ) )
            );
        }
    }

    // Preload critical CSS
    $critical_dir = get_template_directory() . '/dist/critical';
    $critical_url = get_template_directory_uri() . '/dist/critical';

    if ( is_dir( $critical_dir ) ) {
        $template_name = is_singular() ? 'single' : 'index';
        $critical_file = $critical_dir . '/' . $template_name . '-critical.css';

        if ( file_exists( $critical_file ) ) {
            $preloads[] = sprintf(
                '<link rel="preload" href="%s/%s-critical.css" as="style">',
                esc_url( $critical_url ),
                esc_attr( $template_name )
            );
        }
    }

    // Output preload tags
    foreach ( $preloads as $preload ) {
        echo $preload . "
";
    }
}

add_action( 'wp_head', __NAMESPACE__ . '\preload_assets', 2 );

/**
 * DNS prefetch for external resources
 */
function dns_prefetch(): void {
    $domains = array(
        '//fonts.googleapis.com',
        '//fonts.gstatic.com',
    );

    foreach ( $domains as $domain ) {
        printf(
            '<link rel="dns-prefetch" href="%s">' . "
",
            esc_url( $domain )
        );
    }
}

add_action( 'wp_head', __NAMESPACE__ . '\dns_prefetch', 1 );
